### ISSUE TITLE
libvirt required?

### ISSUE THREAD

**Issue by emsearcy** [jfut/ganeti-rpm#14]
Are you sure that libvirtd is required?  It seems you are installing and enabling the libvirtd service (though not the libvirt guest starter), and also disabling libvirtd later on for Xen.

I'm successfully running KVM Ganeti clusters without libvirtd, and also I see no mention of libvirt in the upstream Ganeti installation guide.

The only reason I could see to run the libvirtd service is if one is using it for bridge configuration (on el6 it defaults to setting up a NAT bridge), but you already have steps to set up a bridge by hand (and I think manual bridge setup is preferred to libvirt anyhow).

**Comment by jfut** [comment]
Thanks! You are right. I fixed it.
