### ISSUE TITLE
Plans on upgrading Ganeti 2.13 to CentOS 6

### ISSUE THREAD

**Issue by andronat** [jfut/ganeti-rpm#16]
Hello, I was wondering if there are any plans on upgrading the CentOS 6 rpms to Ganeti 2.13

**Comment by jfut** [comment]
A build of Ganeti 2.12 on CentOS 6 failed due to dependency problems(such as ghc-lens version) of Haskell provided by CentOS and EPEL.

If you install Haskell from a source instead of EPEL, you can build Ganeti 2.12 or later on CentOS 6.

**Comment by andronat** [comment]
Thank you @jfut for your answer
