### ISSUE TITLE
Implement support vlan aware bridge

### ISSUE THREAD

**Issue by alfonso-escribano** [jfut/ganeti-rpm#28]
I have seen this issue https://github.com/ganeti/ganeti/issues/1387  that is resolved with this PR: https://github.com/ganeti/ganeti/pull/1395

Could be possible to implement it into ganeti-rpm rpm packages?

**Comment by jfut** [comment]
Thanks for PR! I've merged your PR. Please wait a few days for the RPM package to be released.

**Comment by jfut** [comment]
Ganeti 2.16.2-1 RPM released!
https://github.com/jfut/ganeti-rpm/releases/tag/v2.16.2-1
