### ISSUE TITLE
CentOS 8/RHEL 8 support

### ISSUE THREAD

**Issue by jfut** [jfut/ganeti-rpm#32]
When I tried it before, the Haskel package required to build Ganeti provided by EPEL was not released yet and could not be built.

**Comment by jfut** [comment]
I've started development for CentOS 8/RHEL 8.
https://github.com/jfut/ganeti-rpm/tree/el8

**Comment by jfut** [comment]
For the upgrade path, we need to provide at least one identical version for both el7 and el8.

**Comment by jfut** [comment]
Hmmm, it's very difficult to build.

<details>
  <summary>CentOS 8 build status details</summary>

- GANETI_DEPENDS_PACKAGES1="ghc-Crypto ghc-curl ghc-regex-pcre"
  - single packages

```bash
# ./package.sh -o no -ip ghc-Crypto
No matching package to install: 'ghc-HUnit-devel'
No matching package to install: 'ghc-QuickCheck-devel'
No matching package to install: 'ghc-random-devel'

# ./package.sh -o no -ip ghc-curl
OK

# ./package.sh -o no -ip ghc-regex-pcre
No matching package to install: 'ghc-regex-base-devel'
```

- GANETI_DEPENDS_PACKAGES2="ghc-base-orphans ghc-tagged ghc-contravariant ghc-distributive ghc-comonad ghc-semigroupoids"
  - (base-orphans | tagged -> (contravariant | distributive) -> comonad)) -> semigroupoids

```
# ./package.sh -o no -ip ghc-base-orphans
OK

# ./package.sh -o no -ip ghc-tagged
template-haskell >=2.8 && <2.12
error: Bad exit status from /var/tmp/rpm-tmp.dcikAg (%build)

# ./package.sh -o no -ip ghc-contravariant
No matching package to install: 'ghc-transformers-compat-devel'

# ./package.sh -o no -ip ghc-distributive
No matching package to install: 'ghc-transformers-compat-devel'

# ./package.sh -o no -ip ghc-comonad
No matching package to install: 'ghc-semigroups-devel'

# ./package.sh -o no -ip ghc-semigroupoids
May be OK
```

- GANETI_DEPENDS_PACKAGES3="ghc-bifunctors ghc-profunctors ghc-generic-deriving ghc-reflection ghc-lens"
  - (bifunctors | profunctors | generic-derivin | reflectiong) -> lens

```
# ./package.sh -o no -ip ghc-bifunctors
May be OK

# ./package.sh -o no -ip ghc-profunctors
May be OK

# ./package.sh -o no -ip ghc-generic-deriving
template-haskell >=2.4 && <2.11
error: Bad exit status from /var/tmp/rpm-tmp.NLOEnW (%build)

# ./package.sh -o no -ip ghc-reflection
May be OK

# ./package.sh -o no -ip ghc-lens
No matching package to install: 'ghc-MonadCatchIO-transformers-devel'
No matching package to install: 'ghc-hashable-devel'
No matching package to install: 'ghc-mtl-devel'
No matching package to install: 'ghc-parallel-devel'
No matching package to install: 'ghc-semigroups-devel'
No matching package to install: 'ghc-split-devel'
No matching package to install: 'ghc-text-devel'
No matching package to install: 'ghc-transformers-compat-devel'
No matching package to install: 'ghc-unordered-containers-devel'
No matching package to install: 'ghc-vector-devel'
No matching package to install: 'ghc-void-devel'
```

- GANETI_DEPENDS_PACKAGES4="ghc-PSQueue ghc-clock ghc-bytestring-builder ghc-zlib-bindings ghc-io-streams"
  - mond/metad dependencies
  - ghc-PSQueue | ghc-clock | ghc-bytestring-builder -> ghc-zlib-bindings -> ghc-io-streams

```
# ./package.sh -o no -ip ghc-PSQueue
OK

# ./package.sh -o no -ip ghc-clock
OK

# ./package.sh -o no -ip ghc-bytestring-builder
Running Haddock on library for bytestring-builder-0.10.8.2.0..
haddock: No input file(s).
error: Bad exit status from /var/tmp/rpm-tmp.lkZv4U (%build)

# ./package.sh -o no -ip ghc-zlib-bindings
No matching package to install: 'ghc-zlib-devel'

# ./package.sh -o no -ip ghc-io-streams
No matching package to install: 'ghc-attoparsec-devel'
No matching package to install: 'ghc-network-devel'
No matching package to install: 'ghc-primitive-devel'
No matching package to install: 'ghc-text-devel'
No matching package to install: 'ghc-vector-devel'
```

- GANETI_DEPENDS_PACKAGES5="ghc-enumerator ghc-attoparsec-enumerator ghc-blaze-builder-enumerator ghc-bytestring-mmap ghc-zlib-enum ghc-snap-core ghc-snap-server"
  - mond/metad dependencies
  - ghc-enumerator -> (ghc-attoparsec-enumerator ghc-blaze-builder-enumerator
  - ghc-bytestring-mmap ghc-zlib-enum) -> ghc-snap-core -> ghc-snap-server

```
# ./package.sh -o no -ip ghc-enumerator
No matching package to install: 'ghc-text-devel'

# ./package.sh -o no -ip ghc-attoparsec-enumerator
No matching package to install: 'ghc-attoparsec-devel'
No matching package to install: 'ghc-text-devel'

# ./package.sh -o no -ip ghc-blaze-builder-enumerator
May be OK

# ./package.sh -o no -ip ghc-bytestring-mmap
OK

# ./package.sh -o no -ip ghc-zlib-enum
May be OK

# ./package.sh -o no -ip ghc-snap-core
No matching package to install: 'ghc-HUnit-devel'
No matching package to install: 'ghc-MonadCatchIO-transformers-devel'
No matching package to install: 'ghc-attoparsec-devel'
No matching package to install: 'ghc-blaze-builder-devel'
No matching package to install: 'ghc-case-insensitive-devel'
No matching package to install: 'ghc-hashable-devel'
No matching package to install: 'ghc-mtl-devel'
No matching package to install: 'ghc-old-locale-devel'
No matching package to install: 'ghc-random-devel'
No matching package to install: 'ghc-regex-posix-devel'
No matching package to install: 'ghc-text-devel'
No matching package to install: 'ghc-unix-compat-devel'
No matching package to install: 'ghc-unordered-containers-devel'
No matching package to install: 'ghc-vector-devel'

# ./package.sh -o no -ip ghc-snap-server
No matching package to install: 'ghc-MonadCatchIO-transformers-devel'
No matching package to install: 'ghc-attoparsec-devel'
No matching package to install: 'ghc-blaze-builder-devel'
No matching package to install: 'ghc-case-insensitive-devel'
No matching package to install: 'ghc-mtl-devel'
No matching package to install: 'ghc-network-devel'
No matching package to install: 'ghc-old-locale-devel'
No matching package to install: 'ghc-text-devel'
No matching package to install: 'ghc-unix-compat-devel'
```

</details>

**Comment by ramereth** [comment]
Yeah, it looks like they need some help getting all the deps included based on this thread: https://lists.fedoraproject.org/archives/list/epel-devel@lists.fedoraproject.org/thread/NRMA7ZNHJGTDEOU37XTUQJL5DVFJM42A/#NRMA7ZNHJGTDEOU37XTUQJL5DVFJM42A

You might want to just try and pull the srpms from Fedora in the meantime which is what I've been doing for other EL8 packages that haven't made it to epel yet.

**Comment by jfut** [comment]
Thanks for the the information.

I was able to build some packages using the c8 branch obtained from https://git.centos.org/.
However, due to the dependencies of old Haskell packages on which ganeti 2.x depends, I have not yet succeeded in building all the necessary libraries.

I feel it would be better to migrate el7 to ganeti 3.x first, and then build ganeti 3.x for el8 from the first release.

Another idea is to build ganeti using `stack`/`cabal` instead of building and releasing Haskell's RPM packages, in order to get away from Haskell dependency hell.

**Comment by ramereth** [comment]
> Thanks for the the information.
> 
> I was able to build some packages using the c8 branch obtained from https://git.centos.org/.
> However, due to the dependencies of old Haskell packages on which ganeti 2.x depends, I have not yet succeeded in building all the necessary libraries.

Ah, that's unfortunate.

> I feel it would be better to migrate el7 to ganeti 3.x first, and then build ganeti 3.x for el8 from the first release.

If Ganeti 3.x uses newer libraries, that might be a good route to focus on. That would allow users to migrate with the same release of Ganeti at least. 

> Another idea is to build ganeti using `stack`/`cabal` instead of building and releasing Haskell's RPM packages, in order to get away from Haskell dependency hell.

I guess it depends how far out Ganeti 3.x is from being released. But it might be worth looking into at least since those deps are only needed with _building_ Ganeti, not running it.
