### ISSUE TITLE
Build RPM packages using Github Actions

### ISSUE THREAD

**Issue by jfut** [jfut/ganeti-rpm#36]
Improve the build process.

**Comment by ramereth** [comment]
Let me know if you want a US based mirror for the rpms. I can help with that.

**Comment by jfut** [comment]
Thank you for your kind offer. I'm interested in it.
What should I prepare for the mirror?

**Comment by ramereth** [comment]
I can pull from you via an rsync fairly easily unless you want to push the updates to us.

**Comment by jfut** [comment]
Thanks! I will try to set up an rsync server once the ganeti-3.0.0 RPM build and release is ready.

**Comment by jfut** [comment]
Successfully built using GitHub Actions.

https://github.com/jfut/ganeti-rpm/actions/runs/517360585
