### ISSUE TITLE
Set up an rsync server for a mirror server

### ISSUE THREAD

**Issue by jfut** [jfut/ganeti-rpm#38]
Thanks @ramereth ! (#36)

**Comment by jfut** [comment]
@ramereth I have set up the rsync server. Could you confirm that you can mirror it?

```bash
$ rsync jfut.integ.jp::
ganeti          Ganeti RPM Packages
```

If you let me know the URL of your mirror server, I will add it to the `mirrorlist` and release a new `integ-ganeti-release` RPM.

**Comment by ramereth** [comment]
This has been deployed to: https://ftp.osuosl.org/pub/ganeti-rpm/

It's set to sync hourly at the 37th minute.

**Comment by jfut** [comment]
Thanks so much @ramereth and the OSU Open Source Lab!

I added it to the `baseurl`, which allows to describe directly multiple URLs, and confirmed that the fastestmirror plugin chooses the one with the fastest response.

**Comment by jfut** [comment]
I just released `integ-ganeti-release-7-3.el7.noarch.rpm` and `integ-ganeti-release-8-1.el8.noarch.rpm`!
