### ISSUE TITLE
Switch %build make to use macro

### ISSUE THREAD

**Issue by rowlap** [jfut/ganeti-rpm#49]
ganeti.spec#L183 uses plain `make`, but there's some [distro policy](https://fedoraproject.org/wiki/Changes/UseMakeBuildInstallMacro) around using `%make_build` instead.

When I test this on a high-CPU count server, the wallclock time to build the RPMs halves, due to the underlying `make -j ...`.

The `%make_build` macro (added in Jan 2014) looks to be available on RHEL7 and later.

Happy to provide a PR, although it's a one-line change :)

**Comment by jfut** [comment]
Sorry I am so late to notice your message, PR is welcome😄

**Comment by rowlap** [comment]
The python packages don't use make.

socat does, but with `_smp_mflags` which is already the performance boost we're looking for. There is an [existing pull request](https://src.fedoraproject.org/rpms/socat/pull-request/1) upstream to change it to use the macros, so I've left it untouched.

**Comment by jfut** [comment]
Thanks for the issue. Build time is now faster.

Run on my local environment:

$ ./build-rpm -a -ucbi

Before: 1407 seconds (make)
After: 924 seconds (%make_build)
